name: "rwilkersonGH23's Action in Action"
description: 'Greets someone and returns always 42'
inputs:
  who-to-greet: # id of input
    descripton: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer: # id of output
    description: 'The answer to everything (always 42)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
